"use client";
import { useState } from "react";
import { ArrowLeft, KeyRound, LockKeyhole, UserRoundPlus } from "lucide-react";

type Mode = "login" | "signup" | "reset";
const passwordHelp = "https://help.openai.com/en/articles/4936828-resetting-or-changing-your-chatgpt-password";
export default function AuthPortal({ signInPath }: { signInPath:string }) {
  const [mode, setMode] = useState<Mode>("login");
  return <main className="auth-page"><div className="auth-shell"><section className="auth-story"><img src="/kawuo-logo.png" alt="KAWUO logo"/><div><span className="auth-overline">KARAMOJA WOMEN UMBRELLA ORGANISATION</span><h1>IT support that stays with you from request to resolution.</h1><p>Submit an issue, follow its progress, and tell us whether the solution worked.</p></div><div className="auth-story-foot">KAWUO · Private staff service desk</div></section>
    <section className="auth-card" aria-live="polite"><div className="auth-tabs" role="tablist" aria-label="Account options"><button role="tab" aria-selected={mode==="login"} className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Sign in</button><button role="tab" aria-selected={mode==="signup"} className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Create account</button><button role="tab" aria-selected={mode==="reset"} className={mode==="reset"?"active":""} onClick={()=>setMode("reset")}>Password help</button></div>
      {mode==="login"?<div className="auth-content"><div className="auth-icon"><LockKeyhole size={23}/></div><span className="eyebrow">WELCOME BACK</span><h2>Sign in to the service desk</h2><p>Use the exact email address invited by KAWUO. You will return to your requests after secure sign-in.</p><a className="primary-button auth-primary" href={signInPath} target="_top">Continue to secure sign-in</a><div className="auth-inline"><button onClick={()=>setMode("signup")}>Create an account</button><button onClick={()=>setMode("reset")}>Forgot password?</button></div></div>
      :mode==="signup"?<div className="auth-content"><div className="auth-icon"><UserRoundPlus size={23}/></div><span className="eyebrow">NEW STAFF ACCOUNT</span><h2>Create your account</h2><p>First create or use a ChatGPT sign-in with your invited KAWUO email. After signing in, complete your staff profile; IT approves the role.</p><a className="primary-button auth-primary" href="https://chatgpt.com/" target="_blank" rel="noreferrer">Open account sign-up</a><a className="secondary-button auth-secondary" href={signInPath} target="_top">I already have an account</a><small>An app profile alone does not grant access. The Site owner must invite your email to this private Site.</small></div>
      :<div className="auth-content"><div className="auth-icon"><KeyRound size={23}/></div><span className="eyebrow">ACCOUNT RECOVERY</span><h2>Forgot your password?</h2><p>Password recovery is handled by the sign-in provider. Follow its reset steps, then return here with your invited email.</p><a className="primary-button auth-primary" href={passwordHelp} target="_blank" rel="noreferrer">Open password reset help</a><small>If you sign in with Google, Microsoft, or Apple, recover your password with that provider.</small><button className="auth-back" onClick={()=>setMode("login")}><ArrowLeft size={16}/> Back to sign in</button></div>}
    </section></div><footer className="auth-footer">© {new Date().getFullYear()} KAWUO · Systems Developer <strong>LOMER Francis Peter</strong>, IT-KAWUO</footer></main>;
}
