"use client";
import { useCallback, useEffect, useState } from "react";
import { Download, Printer, BarChart3 } from "lucide-react";
type ReportTicket={id:string;title:string;category:string;priority:string;status:string;assignee:string;requester_name:string;created_at:string;resolved_at:string|null};
type Report={month:string;generatedAt:string;summary:{submitted:number;resolved:number;backlog:number;urgent:number;averageResolutionHours:number|null};categoryCounts:[string,number][];priorityCounts:[string,number][];feedbackSummary:{total:number;satisfied:number;unresolved:number};feedbackComments:{ticket_id:string;title:string;requester_name:string;satisfied:number;comment:string;created_at:string}[];tickets:ReportTicket[];hasMore:boolean};
const label=(m:string)=>new Date(`${m}-01T00:00:00Z`).toLocaleDateString("en-UG",{month:"long",year:"numeric",timeZone:"UTC"});
const date=(s:string)=>new Date(s).toLocaleDateString("en-UG",{day:"numeric",month:"short",year:"numeric"});
export default function MonthlyReport(){
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async(m:string)=>{setLoading(true);try{const r=await fetch(`/api/reports?month=${encodeURIComponent(m)}`,{cache:"no-store"});const d=await r.json() as Report&{error?:string};if(!r.ok)throw new Error(d.error||"Could not load report.");setReport(d);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load report.");setReport(null);}finally{setLoading(false);}},[]);
  useEffect(()=>{void load(month);},[load,month]);
  function downloadCsv(){if(!report)return;window.location.href=`/api/reports?month=${encodeURIComponent(report.month)}&format=csv`;}
  const maxCategory=Math.max(1,...(report?.categoryCounts.map(x=>x[1])||[]));
  return <section className="workspace-section"><div className="page-heading"><div><div className="eyebrow">MANAGEMENT REPORTING</div><h1>Monthly IT report</h1><p>Review real service records, then save the report as PDF for management submission.</p></div></div><div className="report-toolbar"><label>Reporting month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div><button className="secondary-button" onClick={downloadCsv} disabled={!report}><Download size={16}/> Download CSV</button><button className="primary-button" onClick={()=>window.print()} disabled={!report}><Printer size={16}/> Print / Save PDF</button></div></div>
    {error&&<div className="banner error" role="alert">{error}<button onClick={()=>void load(month)}>Retry</button></div>}
    {loading?<div className="panel report-loading">Preparing monthly report…</div>:report&&<article className="report-sheet" id="management-report"><div className="report-head"><img src="/kawuo-logo.png" alt="KAWUO logo"/><div><span>KARAMOJA WOMEN UMBRELLA ORGANISATION</span><h2>IT Service Management Report</h2><p>{label(report.month)} · Prepared for management</p></div></div><div className="report-subhead"><span>Reporting period: {label(report.month)}</span><span>Generated: {date(report.generatedAt)}</span></div>
      <div className="report-metrics"><div><span>Requests received</span><strong>{report.summary.submitted}</strong></div><div><span>Requests resolved</span><strong>{report.summary.resolved}</strong></div><div><span>Backlog at month end</span><strong>{report.summary.backlog}</strong></div><div><span>Urgent requests</span><strong>{report.summary.urgent}</strong></div></div>
      <div className="report-insight"><BarChart3 size={20}/><p>{report.summary.submitted} IT {report.summary.submitted===1?"request was":"requests were"} recorded in {label(report.month)}. {report.summary.resolved} {report.summary.resolved===1?"request was":"requests were"} resolved during the month, including older requests. {report.summary.averageResolutionHours===null?"No completed requests are available for a resolution-time average.":`Average time from submission to resolution was ${report.summary.averageResolutionHours} hours for completed requests.`}</p></div>
      <div className="report-two"><div><h3>Requests by category</h3>{report.categoryCounts.length?report.categoryCounts.map(([name,count])=><div className="report-bar" key={name}><div><span>{name}</span><strong>{count}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.round(count/maxCategory*100)}%`}}/></div></div>):<p className="muted-copy">No requests were submitted this month.</p>}</div><div><h3>Priority breakdown</h3><div className="priority-summary">{report.priorityCounts.length?report.priorityCounts.map(([name,count])=><div key={name}><span className={`priority-pill ${name.toLowerCase()}`}>{name}</span><strong>{count}</strong></div>):<p className="muted-copy">No requests to classify.</p>}</div></div></div>
      <h3>Requester feedback</h3><div className="feedback-summary"><div><strong>{report.feedbackSummary.total}</strong><span>Responses received</span></div><div><strong>{report.feedbackSummary.satisfied}</strong><span>Confirmed resolved</span></div><div><strong>{report.feedbackSummary.unresolved}</strong><span>Reopened by requesters</span></div><div><strong>{report.feedbackSummary.total?Math.round(report.feedbackSummary.satisfied/report.feedbackSummary.total*100):0}%</strong><span>Satisfaction among responses</span></div></div>
      {report.feedbackComments.length ? <div className="report-feedback-list">{report.feedbackComments.map(item=><div key={`${item.ticket_id}-${item.created_at}`}><span className={item.satisfied?"feedback-positive":"feedback-negative"}>{item.satisfied?"Resolved to satisfaction":"Needs more work"}</span><strong>{item.ticket_id} · {item.title}</strong><p>{item.comment || "No additional comment."}</p><small>{item.requester_name} · {date(item.created_at)}</small></div>)}</div> : <p className="muted-copy">No resolution feedback was submitted this month.</p>}
      <h3>Requests submitted this month</h3>{report.hasMore && <p className="muted-copy">Showing the latest 100 requests here. Download CSV for the complete monthly list.</p>}<div className="report-table-wrap"><table><thead><tr><th>ID</th><th>Request</th><th>Category</th><th>Priority</th><th>Status</th><th>Submitted</th></tr></thead><tbody>{report.tickets.length?report.tickets.map(t=><tr key={t.id}><td>{t.id}</td><td>{t.title}</td><td>{t.category}</td><td>{t.priority}</td><td>{t.status}</td><td>{date(t.created_at)}</td></tr>):<tr><td colSpan={6}>No requests were submitted during this month.</td></tr>}</tbody></table></div>
      <div className="report-foot"><span>Example tickets are excluded from this report.</span><span>© {new Date().getFullYear()} KAWUO · Systems Developer: LOMER Francis Peter, IT-KAWUO</span></div>
    </article>}
  </section>;
}
