"use client";
import { useCallback, useEffect, useState } from "react";
import { Monitor, ShieldCheck, Headphones, ArrowUpRight } from "lucide-react";
type Session = { id:string; requester_id:string; requester_name:string; requester_email:string; device:string; issue:string; ticket_id:string|null; status:string; assignee:string; notes:string; consent_acknowledged:number; created_at:string; updated_at:string };
const statuses=["Requested","Scheduled","In session","Completed","Cancelled"];
export default function RemoteDesk({support}:{support:boolean}) {
  const [sessions,setSessions]=useState<Session[]>([]),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [form,setForm]=useState({device:"",issue:"",ticketId:"",consent:false});
  const [edit,setEdit]=useState({status:"Requested",assignee:"",notes:""});
  const load=useCallback(async()=>{try{const r=await fetch("/api/remote",{cache:"no-store"});const d=await r.json() as {sessions?:Session[];error?:string};if(!r.ok)throw new Error(d.error||"Could not load remote requests.");setSessions(d.sessions||[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load remote requests.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const current=sessions.find(s=>s.id===selected);
  function open(s:Session){setSelected(s.id);setEdit({status:s.status,assignee:s.assignee,notes:s.notes});setError("");}
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");setNotice("");try{const r=await fetch("/api/remote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json() as {id?:string;error?:string};if(!r.ok)throw new Error(d.error||"Could not request help.");setForm({device:"",issue:"",ticketId:"",consent:false});await load();setNotice(`Remote assistance request ${d.id} submitted. IT will arrange a Quick Assist session.`);}catch(e){setError(e instanceof Error?e.message:"Could not request help.");}finally{setSaving(false);}}
  async function update(status:string){if(!current)return;setSaving(true);setError("");setNotice("");try{const r=await fetch("/api/remote",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:current.id,status,assignee:edit.assignee,notes:edit.notes})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Could not update request.");await load();setNotice(`${current.id} updated.`);}catch(e){setError(e instanceof Error?e.message:"Could not update request.");}finally{setSaving(false);}}
  return <section className="workspace-section"><div className="page-heading"><div><div className="eyebrow">CONSENT-BASED SUPPORT</div><h1>Remote assistance</h1><p>Arrange Windows software troubleshooting with IT through Quick Assist.</p></div></div>
    {error&&<div className="banner error" role="alert">{error}<button onClick={()=>void load()}>Retry</button></div>}{notice&&<div className="banner success" role="status">{notice}</div>}
    <div className="remote-intro"><div className="remote-icon"><Monitor size={24}/></div><div><strong>How a session works</strong><p>Both people open Windows Quick Assist (Windows key + Ctrl + Q). IT gives you a temporary six-digit code. Enter it on your PC and choose Allow. Full control requires a separate approval on your PC. You may end the session at any time.</p><a href="https://support.microsoft.com/en-us/windows/apps/solve-pc-problems-remotely-using-quick-assist" target="_blank" rel="noreferrer">Microsoft Quick Assist guide <ArrowUpRight size={14}/></a></div></div>
    <div className="remote-grid"><form className="panel remote-form" onSubmit={submit}><div className="panel-heading"><h2>Request a session</h2><Headphones size={20}/></div><label>Computer or device<input required minLength={3} maxLength={120} placeholder="e.g. Finance laptop" value={form.device} onChange={e=>setForm({...form,device:e.target.value})}/></label><label>What needs troubleshooting?<textarea required minLength={10} maxLength={2000} rows={5} placeholder="Describe the software issue..." value={form.issue} onChange={e=>setForm({...form,issue:e.target.value})}/></label><label>Related ticket ID <small>Optional</small><input maxLength={64} placeholder="KAW-..." value={form.ticketId} onChange={e=>setForm({...form,ticketId:e.target.value})}/></label><label className="consent-row"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>I understand that I must approve screen sharing and any control request on my device. I can stop the session at any time.</span></label><button className="primary-button" disabled={saving}>{saving?"Submitting…":"Request remote help"}</button></form>
    <div className="panel remote-list"><div className="panel-heading"><div><h2>{support?"Remote support queue":"My remote requests"}</h2><span>{sessions.length} requests</span></div></div>{loading?<p>Loading requests…</p>:sessions.length?<div className="remote-rows">{sessions.map(s=><button className={`remote-row ${selected===s.id?"selected":""}`} key={s.id} onClick={()=>open(s)}><div><strong>{s.device}</strong><small>{s.id} · {support?s.requester_name:new Date(s.created_at).toLocaleDateString("en-UG")}</small></div><span className={`remote-status ${s.status.toLowerCase().replace(" ","-")}`}>{s.status}</span></button>)}</div>:<div className="empty-state"><Monitor size={28}/><strong>No remote requests yet</strong><p>Use the form to arrange help with a device.</p></div>}
      {current&&<div className="remote-detail"><div className="panel-heading"><h2>{current.id}</h2><span>{new Date(current.created_at).toLocaleDateString("en-UG")}</span></div><p><strong>{current.device}</strong> · {current.requester_name}</p><p>{current.issue}</p>{current.ticket_id&&<p>Related ticket: {current.ticket_id}</p>}{support?<div className="remote-edit"><label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Assigned IT officer<input maxLength={100} value={edit.assignee} onChange={e=>setEdit({...edit,assignee:e.target.value})}/></label><label>Outcome notes<textarea rows={3} maxLength={2000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})} placeholder="Record actions and outcome..."/></label><button className="primary-button" disabled={saving} onClick={()=>void update(edit.status)}>Save session</button></div>:<><p className="account-hint"><ShieldCheck size={15}/> You approve access in Quick Assist on your own computer. This portal never stores the temporary session code.</p>{current.status!=="Cancelled"&&current.status!=="Completed"&&<button className="secondary-button" disabled={saving} onClick={()=>void update("Cancelled")}>Cancel request</button>}</>}</div>}
    </div></div>
  </section>;
}
