"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw, Search, ShieldCheck, UserRoundPlus } from "lucide-react";
import { KNOWN_JOB_TITLES, ROLE_GROUPS, STAFF_ROLES, TECHNICAL_ROLES } from "../lib/roles";

type Staff = { email: string; name: string; department: string; role: string; active: number; self_requested: number };

export default function StaffDirectory({ admin }: { admin: boolean }) {
  const [staff, setStaff] = useState<Staff[]>([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [query, setQuery] = useState(""), [group, setGroup] = useState("All roles");
  const [form, setForm] = useState({ email: "", name: "", department: "", role: "Staff" });
  const load = useCallback(async () => { try { const r = await fetch("/api/staff", {cache:"no-store"}); const d = await r.json() as { staff?: Staff[]; error?: string }; if (!r.ok) throw new Error(d.error || "Could not load people."); setStaff(d.staff || []); setError(""); } catch(e) {setError(e instanceof Error ? e.message : "Could not load people.");} finally {setLoading(false);} }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => staff.filter(s => {
    const match = !query || `${s.name} ${s.email} ${s.department} ${s.role}`.toLowerCase().includes(query.toLowerCase());
    return match && (group === "All roles" || (group === "Technical support" ? s.role === "Systems Administrator" || TECHNICAL_ROLES.includes(s.role) : s.role === group));
  }), [staff, query, group]);
  async function add(e: React.FormEvent) { e.preventDefault(); setSaving("new"); setError(""); setNotice(""); try { const r = await fetch("/api/staff", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json() as {error?:string}; if(!r.ok) throw new Error(d.error||"Could not add staff."); setForm({email:"",name:"",department:"",role:"Staff"}); await load(); setNotice("Staff profile saved. Invite this email through the private Site sharing settings before the person signs in."); } catch(e){setError(e instanceof Error?e.message:"Could not add staff.");} finally{setSaving("");} }
  async function update(member: Staff, next: {role?: string; active?: boolean}) { setSaving(member.email); setError(""); setNotice(""); try { const r=await fetch("/api/staff",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:member.email,role:next.role??member.role,active:next.active??Boolean(member.active)})}); const d=await r.json() as {error?:string}; if(!r.ok) throw new Error(d.error||"Could not update staff."); await load(); setNotice(`${member.name}'s profile updated.`); } catch(e){setError(e instanceof Error?e.message:"Could not update staff.");} finally{setSaving("");} }
  return <section className="workspace-section"><div className="page-heading"><div><div className="eyebrow">KAWUO PEOPLE</div><h1>People & roles</h1><p>Find technical specialists and organisational contacts. Roles control who can manage requests and reports.</p></div></div>
    <div className="role-catalog">{ROLE_GROUPS.map(g => <div className="panel" key={g.title}><h2>{g.title}</h2><div>{g.roles.map(role => <span className="role-tag" key={role}>{role}</span>)}</div></div>)}</div>
    {error && <div className="banner error" role="alert">{error}<button onClick={() => void load()}>Retry</button></div>}{notice && <div className="banner success" role="status">{notice}</div>}
    <div className={`staff-layout ${admin ? "" : "directory-only"}`}>
      {admin && <form className="panel staff-add" onSubmit={add}><div className="panel-heading"><h2>Add staff member</h2><UserRoundPlus size={20}/></div><label>Full name<input required minLength={2} maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Staff member's name"/></label><label>Email address<input required type="email" maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@kawuo.org"/></label><label>Department<input maxLength={100} value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="e.g. Programmes"/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{STAFF_ROLES.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary-button" disabled={Boolean(saving)}>{saving==="new"?"Saving…":"Add staff"}</button><p className="account-hint">Private Site sharing also requires an invitation to the new staff email.</p></form>}
      <div className="panel staff-list"><div className="panel-heading"><div><h2>Staff directory</h2><span>{visible.length} of {staff.length} profiles</span></div><button className="icon-button" onClick={() => void load()} aria-label="Refresh staff list"><RefreshCw size={17}/></button></div>
        <div className="directory-filters"><label className="search-box"><Search size={17}/><input aria-label="Search staff" placeholder="Search name, email, department…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter staff role" value={group} onChange={e=>setGroup(e.target.value)}><option>All roles</option><option>Technical support</option>{STAFF_ROLES.map(x=><option key={x}>{x}</option>)}</select></div>
        {loading?<p>Loading people…</p>:visible.length?<div className="staff-rows">{visible.map(s=><div className="staff-row" key={s.email || s.role}><div className="staff-identity"><div className="staff-avatar">{s.name.slice(0,1).toUpperCase()}</div><div><strong>{s.name}</strong><span>{KNOWN_JOB_TITLES[s.email] || s.role}{s.department?` · ${s.department}`:""}</span><span>{s.email || "IT administration"} · Portal role: {s.role}</span></div></div>{s.role==="Systems Administrator"?<div className="locked-role"><ShieldCheck size={16}/> Systems Administrator</div>:admin?<div className="staff-controls"><select aria-label={`Role for ${s.name}`} value={s.role} disabled={Boolean(saving)} onChange={e=>void update(s,{role:e.target.value})}>{STAFF_ROLES.map(x=><option key={x}>{x}</option>)}</select><button className={s.active?"state-button active":"state-button"} disabled={Boolean(saving)} onClick={()=>void update(s,{active:!s.active})}>{s.active?"Active":s.self_requested?"Approve":"Enable"}</button></div>:null}{!s.active && s.self_requested && <span className="pending-label">Awaiting approval: {s.role}</span>}</div>)}</div>:<p className="directory-empty">No people match this search.</p>}</div>
    </div>
  </section>;
}
